name: Test Custom Action
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Custom Action
        uses: arthursady/auto-release-tag-generator@v0.0.3
        with:
            prefix: "test@test-"
            buildNumber: ${{github.run_number}}