name: Test Custom Action
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Custom Action
        uses: arthursady/auto-release-tag-generator@v0.0.1
        with:
            prefix: "test@test-"
            buildNumber: ${{github.run_number}}